#version: '3.8'

services:
  heart_disease_prediction_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

    environment:
      - PYTHONUNBUFFERED=1
